= Clock Library for Arduino =

It substitutes a RTC module but needs to configure time each time Arduino turns on or reset

For more information about this library please visit us at
https://github.com/canalBrincandoComIdeias


== Reference ==

=== Include ===
#include "Clock.h"

=== Instance ===
Clock myClock;

=== Methods ===

//Adjusts the time (to be used on SETUP) -> Acerta o horario (para uso no SETUP)
void ajustaHorario(byte hora, byte minuto, byte segundo);
Parameters:
- byte hora:	to inform the hour between 0 and 23 -> Para informar a hora entre 0 e 23
- byte minuto:	to inform the minute 0 to 59 -> Para informar o minuto entre 0 e 59
- byte segundo:	to inform the second 0 to 59 -> Para informar o segundo entre 0 e 59
Return:
- void

	//Retorna o horario atual
	horario horarioAtual();

	//Comparações entre dois horarios
	bool horarioMenor(horario valor1, horario valor2);
	bool horarioMaior(horario valor1, horario valor2);
	bool horarioIgual(horario valor1, horario valor2);
	bool horaMinutoIgual(horario valor1, horario valor2);

	//Adicao
	horario adicionaHoras(horario origem, int horas);
	horario adicionaMinutos(horario origem, int minutos);
	horario adicionaSegundos(horario origem, int segundos);
    horario adicionaMilesimos(horario origem, int milesimos);

	//Conversão
	uint32_t horarioParaMilesimo(horario origem);
	uint32_t horarioParaSegundos(horario origem);
	uint32_t horarioParaMinutos(horario origem);
	horario milesimoParaHorario(uint32_t origem);
	String horaParaTexto(horario origem);

	//Ajuste do relogio quando o millis() zerar (a cada 50 dias aprox.)
	void quandoMillisZerar();



== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
